ublox_moving_base:
  ros__parameters:
    debug: 1
    gnss:
      gps: true
      glonass: true
      galileo: true
      beidu: false
      qzss: false
      sbas: false
    device: /dev/ublox_moving_base
    frame_id: ublox_moving_base
    rate: 10.0                     # in Hz
    nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may 
                                # be either 5 Hz (Dual constellation) or 
                                # 8 Hz (GPS only)
    dynamic_model: airborne2    # Airborne < 2G, 2D fix not supported (3D only), 
                                # Max Alt: 50km
                                # Max Horizontal Velocity: 250 m/s, 
                                # Max Vertical Velocity: 100 m/s
    fix_mode: auto
    enable_ppp: false           # Not supported by C94-M8P
    dr_limit: 0
    usb:
      in: 35
      out: 1
    uart1:
      baudrate: 460800
      in: 0                      # No Input on UART
      out: 32                    # RTCM 3
    dgnss_mode: 3               # Fixed mode
    inf:
      all: true                 # Whether to display all INF messages in console
    publish:
      aid:
        hui: false
      nav:
        posecef: false
        relposned: true
      rxm:
        rtcm: true

    tmode3: 0
